// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOfm23w65cZKq-JHI0BS0hZIAvF6HNVE',
    appId: '1:1013405549637:web:ad9e33ab43008110854f2c',
    messagingSenderId: '1013405549637',
    projectId: 'entregas-pos',
    authDomain: 'entregas-pos.firebaseapp.com',
    databaseURL: 'https://entregas-pos-default-rtdb.firebaseio.com',
    storageBucket: 'entregas-pos.appspot.com',
    measurementId: 'G-J1G50N0JTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aoDmlj7x3dVckaLDq9IY05cg5XV5XB4',
    appId: '1:1013405549637:android:766468ac3f21b54e854f2c',
    messagingSenderId: '1013405549637',
    projectId: 'entregas-pos',
    databaseURL: 'https://entregas-pos-default-rtdb.firebaseio.com',
    storageBucket: 'entregas-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCndWprmIM9R2IDLD_J3XFmgHygtvdxnc',
    appId: '1:1013405549637:ios:f4ce2270a58947ae854f2c',
    messagingSenderId: '1013405549637',
    projectId: 'entregas-pos',
    databaseURL: 'https://entregas-pos-default-rtdb.firebaseio.com',
    storageBucket: 'entregas-pos.appspot.com',
    iosClientId: '1013405549637-p6b1vcamr6opd2k7p824jq0ml4oqs1vr.apps.googleusercontent.com',
    iosBundleId: 'com.renanassisalves.entrega2.entregaFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCndWprmIM9R2IDLD_J3XFmgHygtvdxnc',
    appId: '1:1013405549637:ios:f4ce2270a58947ae854f2c',
    messagingSenderId: '1013405549637',
    projectId: 'entregas-pos',
    databaseURL: 'https://entregas-pos-default-rtdb.firebaseio.com',
    storageBucket: 'entregas-pos.appspot.com',
    iosClientId: '1013405549637-p6b1vcamr6opd2k7p824jq0ml4oqs1vr.apps.googleusercontent.com',
    iosBundleId: 'com.renanassisalves.entrega2.entregaFlutter2',
  );
}
